## s3 슬꺼로 바꿈
#server:
#  port: 0
#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: todak
#    username: todak
#    password: todak
#    tomcat:
#      max-active: 5
#
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MariaDBDialect
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#  servlet:
#    multipart:
#      maxFileSize: 5120MB # 최대 5GB
#      maxRequestSize: 5120MB # 최대 5GB
#
#  application:
#    name: community-service
#
#jwt:
#  secret: secret_key
#  secretKeyRT: secret_key_RT
#  expirationRT: 86400000
#  expiration: 86400000  # 1 day in milliseconds
#
## aws s3 설정
#cloud:
#  aws:
#    credentials:
#      access-key : todak
#      secret-key : todak
#    region:
#      static: ap-northeast-2
#    s3:
#      bucket: todak-file
#eureka:
#  client:
#    serviceUrl:
#      #      eureka의 member-service(서비스)로서 등록됨을 지정하겠다.
#      defaultZone: http://eureka:8761/eureka/


server:
  port: 0

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: todak
    username: todak
    password: todak
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+9
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      #      groupid는 consumer 그룹을 식별하는 id 이다. 동일한 그룹ID를 가진 컨슈머들은 메시지를 분담해서 consume.
      group-id: group_id
      #      가장 처음으로 사용가능한 메시지부터 읽기 시작.
      auto-offset-reset: earliest
  application:
    name: community-service
cloud:
  aws:
    credentials:
      access-key: todak
      secret-key: todak
    region:
      static: ap-northeast-2
    s3:
      bucket: todak-file
eureka:
  client:
    serviceUrl:
      #      eureka의 member-service(서비스)로서 등록됨을 지정하겠다.
      defaultZone: http://localhost:8761/eureka/