# s3 슬꺼로 바꿈
server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope: account_email, profile_nickname
#            redirect-uri: "http://localhost:8080/member-service/login/oauth2/code/kakao" 로컬, 아래는 배포
            redirect-uri: "https://server.todak.site/member-service/login/oauth2/code/kakao"
            client-name: Kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/todaktodak
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      maxFileSize: 5120MB # 최대 5GB
      maxRequestSize: 5120MB # 최대 5GB

  # Email settings
  mail:
    host: ${MAIL_HOST}
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

  redis:
    host: ${REDIS_HOST}
    port: 6379
    #password: 1234
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP}
    consumer:
      #      groupid는 consumer 그룹을 식별하는 id 이다. 동일한 그룹ID를 가진 컨슈머들은 메시지를 분담해서 consume.
      group-id: payment-group
      #      가장 처음으로 사용가능한 메시지부터 읽기 시작.
      auto-offset-reset: earliest
      enable-auto-commit: false
    # chat service 용 추가 설정
    chat:
      consumer:
        group-id: chat-group
        auto-offset-reset: earliest
        enable-auto-commit: false
#  kafka:
#    bootstrap-servers: ${KAFKA_BOOTSTRAP}
#    consumer:
#      group-id: payment-group  # consumer 그룹을 식별하는 ID입니다. 동일한 그룹 ID를 가진 컨슈머들은 메시지를 분담해서 consume합니다.
#      auto-offset-reset: earliest  # 가장 처음으로 사용 가능한 메시지부터 읽기 시작합니다.
#      enable-auto-commit: false
#
#    chat:
#      consumer:
#        group-id: chat-group
#        auto-offset-reset: earliest
#        enable-auto-commit: false

  application:
    name: member-service

jwt:
  secret: ${JWT_SECRET}
  secretKeyRT: ${JWT_SECRET_RT}
  expirationRT: 86400000
  expiration: 86400000  # 1 day in milliseconds

# aws s3 설정
cloud:
  aws:
    credentials:
      access-key : ${AWS_ACCESS_KEY}
      secret-key : ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: ${BUCKET}
eureka:
  client:
    serviceUrl:
      #      eureka의 member-service(서비스)로서 등록됨을 지정하겠다.
      defaultZone: http://localhost:8761/eureka/
aws:
  ses:
    access-key: ${SES_ACCESS}
    secret-key: ${SES_SECRET} # 보안 액세스 키
    region: ap-northeast-2
encryption:
  secret-key: ${ENCRYPTION_SECRET}
fcm:
  secret-file: todak-1f8d0-firebase-adminsdk-tbqa8-b7c41789c9.json
  secret-file-content: ${FIRE_BASE_SDK}
google:
  api:
    key: ${GOOGlE_API_KEY}