version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      # 컨테이너가 시작될 때 지정된 데이터베이스가 자동으로 생성. 이미 있을 때는 아무것도 하지 않는다.
      MYSQL_DATABASE: todaktodak
    #      MYSQL_USER: root
    #      MYSQL_PASSWORD: 1234
    ports:
      - 3310:3306
    volumes:
      - mariadb_data:/var/lib/mysql
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6380:6379
    volumes:
      - redis_data:/data
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mariadb_data:
  redis_data: