spring:
  application:
    name: todak

# 8761이 알려진 Eureka의 포트
server:
  port: todak
eureka:
  client:
#    eureka서버가 자기 자신은 eureka에 등록하지 않겠다는 설정.
    register-with-eureka: todak
    fetch-registry: todak