spring:
  application:
    name: eureka-server

# 8761이 알려진 Eureka의 포트
server:
  port: 8761
eureka:
  client:
#    eureka서버가 자기 자신은 eureka에 등록하지 않겠다는 설정.
    register-with-eureka: false
    fetch-registry: false