apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-deployment
  namespace: todak
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
        - name: todak
          image: 058264257845.dkr.ecr.ap-northeast-2.amazonaws.com/todak-reservation:latest # 수정 필요
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "500Mi"
            requests:
              cpu: "0.5"
              memory: "500Mi"
          env:
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  key: REDIS_HOST
                  name: todak-secret
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: DB_HOST
                  name: todak-secret
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: DB_USERNAME
                  name: todak-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: todak-secret
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: todak-secret
            - name: JWT_SECRET_RT
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET_RT
                  name: todak-secret
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY
                  name: todak-secret
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET_KEY
                  name: todak-secret
            - name: BUCKET
              valueFrom:
                secretKeyRef:
                  key: BUCKET
                  name: todak-secret
            - name: IAM_API
              valueFrom:
                secretKeyRef:
                  key: IAM_API
                  name: todak-secret
            - name: IAM_API_SECRET
              valueFrom:
                secretKeyRef:
                  key: IAM_API_SECRET
                  name: todak-secret
            - name: KAFKA_BOOTSTRAP
              valueFrom:
                secretKeyRef:
                  key: KAFKA_BOOTSTRAP
                  name: todak-secret
            - name: FIRE_BASE_SDK
              valueFrom:
                secretKeyRef:
                  key: padak-todak-firebase-adminsdk-d2ths-d5d3744918.json
                  name: firebase-adminsdk

