# docker 빌드 후 ecr 업로드 및 kubectl apply 

name: deploy todak-padak with k8s
on:
  push:
    branches:
      - prod
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github
        uses: actions/checkout@v2

      - name: install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.25.9"
        id: install
      
      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }} 
          aws-region: ap-northeast-2

      - name: update cluster information
        run: aws eks update-kubeconfig --name todak-padak-cluster --region ap-northeast-2
      
      - name: login ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: eks kubectl delete
        run: |
          kubectl delete -f ./community/k8s/community_depl.yml --ignore-not-found
          kubectl delete -f ./member/k8s/member_depl.yml --ignore-not-found
          kubectl delete -f ./reservation/k8s/reservation_depl.yml --ignore-not-found



# member
      - name: build and push docker member images to ecr
        env:
          REGISTRY: 058264257845.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: todak-member
          # dockerfile이 현재 위치가 아니기 때문에 폴더경로 적어서 명시
        run: | 
          docker build -t $REGISTRY/$REPOSITORY:latest \
          -f ./member/Dockerfile  ./member
          docker push $REGISTRY/$REPOSITORY:latest
      
      - name: eks kubectl apply
        run: |
          kubectl apply -f ./member/k8s/member_depl.yml
          kubectl apply -f ./member/k8s/member_service.yml
          kubectl rollout restart deployment member-deployment -n todak

# reservation
      - name: build and push docker reservation images to ecr
        env:
          REGISTRY: 058264257845.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: todak-reservation
          # dockerfile이 현재 위치가 아니기 때문에 폴더경로 적어서 명시
        run: | 
          docker build -t $REGISTRY/$REPOSITORY:latest \
          -f ./reservation/Dockerfile  ./reservation
          docker push $REGISTRY/$REPOSITORY:latest
      
      - name: eks kubectl apply
        run: |
          kubectl apply -f ./reservation/k8s/reservation_depl.yml
          kubectl apply -f ./reservation/k8s/reservation_service.yml
          kubectl rollout restart deployment reservation-deployment -n todak

# community
      - name: build and push docker community images to ecr
        env:
          REGISTRY: 058264257845.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: todak-community
          # dockerfile이 현재 위치가 아니기 때문에 폴더경로 적어서 명시
        run: | 
          docker build -t $REGISTRY/$REPOSITORY:latest \
          -f ./community/Dockerfile  ./community
          docker push $REGISTRY/$REPOSITORY:latest
      
      - name: eks kubectl apply
        run: |
          kubectl apply -f ./reservation/k8s/community.yml
          kubectl apply -f ./reservation/k8s/community.yml
          kubectl rollout restart deployment community-deployment -n todak